### ISSUE TITLE
usage of getFeat2 function for calculating intergenic region

### ISSUE THREAD

**Issue by madhubioinfo** [Adamtaranto/density-Mapr#1] opened 2017-04-04 11:01 UTC
Hello,
Iam trying to calculate the intergenic region from the gtf file using the sample dataset provided in the package , when am trying to follow the steps its showing following errors
source("getFeat2.R")
library(rtracklayer)
library(GenomicRanges)
library(Rsamtools)
gff=import.gff("Mygtf.gtf")
gffgene<-getFeat2(x=gff,format="gtf",range_types=c("exon")) [when am doing this am getting following error Error: subscript contains invalid names]
Could you please help me in solving the error? or where am going wrong?

**Comment by Adamtaranto** [comment] 2017-04-04 11:44
I recently ran into this error as well. It is caused by a change in the way that GenomicRanges handles feature names, getFeat2 is looking for a column in the GR object that does not exist.

I have a fix for this and will update the repo shortly.

**Comment by madhubioinfo** [comment] 2017-04-04 11:45
thanks alot for replying me and will wait for your fix soon

**Comment by madhubioinfo** [comment] 2017-04-04 11:47
wether is there any difference between the intergenic calculation from compliment bed to this R differs? and I was checking the csv files it had exon intergenic distance, but the distance was varying , how this has been calculated ?

**Comment by Adamtaranto** [comment] 2017-04-05 12:31
See updated density-Mapr-Workflow.R
Bedtools is a whole other thing, but yes, the 'complement' tool is different in that it does not calculate intergenic distances relative to features.

**Closed as completed by Adamtaranto** 2017-04-05 12:31 UTC
