### ISSUE TITLE
Error with getFeat2b

### ISSUE THREAD

**Issue by MarisaMiller** [Adamtaranto/density-Mapr#2] opened 2017-07-05 22:46 UTC
I'm running into an error with this function. Here's what my GFF file looks like:

`##gff-version 3
000000F	EVM	gene	752588	753724	.	-	.	ID=PCA_SD_00137
000000F	EVM	mRNA	752588	753724	.	-	.	ID=PCA_SD_00137-T1;Parent=PCA_SD_00137;note=EggNog:ENOG410PTX5
000000F	EVM	exon	752588	753724	.	-	.	ID=evm.model.000000F.181.exon1;Parent=PCA_SD_00137-T1
000000F	EVM	CDS	752588	753724	.	-	0	ID=cds.evm.model.000000F.181;Parent=PCA_SD_00137-T1
000000F	EVM	start_codon	753722	753724	.	+	.	ID=PCA_SD_00137-T1:start;Parent=PCA_SD_00137-T1
000000F	EVM	stop_codon	752588	752590	.	+	.	ID=PCA_SD_00137-T1:stop;Parent=PCA_SD_00137-T1
000000F	EVM	gene	748793	751796	.	+	.	ID=PCA_SD_00136
000000F	EVM	mRNA	748793	751796	.	+	.	ID=PCA_SD_00136-T1;Parent=PCA_SD_00136;note=EggNog:ENOG410PFEV,BUSCO:EOG09262A6N;db_xref=InterPro:IPR020472,InterPro:IPR001680,InterPro:IPR015943,InterPro:IPR032847,InterPro:IPR019775,InterPro:IPR017986;go_function=protein binding|0005515||IEA;go_process=mRNA splicing, via spliceosome|0000398||IEA;go_component=catalytic step 2 spliceosome|0071013||IEA
000000F	EVM	exon	748793	749071	.	+	.	ID=evm.model.000000F.180.exon1;Parent=PCA_SD_00136-T1
000000F	EVM	exon	749168	749315	.	+	.	ID=evm.model.000000F.180.exon2;Parent=PCA_SD_00136-T1
000000F	EVM	exon	749458	750179	.	+	.	ID=evm.model.000000F.180.exon3;Parent=PCA_SD_00136-T1
000000F	EVM	exon	750261	750408	.	+	.	ID=evm.model.000000F.180.exon4;Parent=PCA_SD_00136-T1
000000F	EVM	exon	750520	750635	.	+	.	ID=evm.model.000000F.180.exon5;Parent=PCA_SD_00136-T1
000000F	EVM	exon	750736	750791	.	+	.	ID=evm.model.000000F.180.exon6;Parent=PCA_SD_00136-T1
000000F	EVM	exon	750896	751050	.	+	.	ID=evm.model.000000F.180.exon7;Parent=PCA_SD_00136-T1
000000F	EVM	exon	751151	751419	.	+	.	ID=evm.model.000000F.180.exon8;Parent=PCA_SD_00136-T1
000000F	EVM	exon	751517	751561	.	+	.	ID=evm.model.000000F.180.exon9;Parent=PCA_SD_00136-T1
000000F	EVM	exon	751791	751796	.	+	.	ID=evm.model.000000F.180.exon10;Parent=PCA_SD_00136-T1`

Here's what the head looks like after importing with import.gff:

head(sd80_gff)
GRanges object with 6 ranges and 13 metadata columns:
      seqnames           ranges strand |   source        type     score     phase                          ID          Parent
         <Rle>        <IRanges>  <Rle> | <factor>    <factor> <numeric> <integer>                 <character> <CharacterList>
  [1]  000000F [752588, 753724]      - |      EVM        gene      <NA>      <NA>                PCA_SD_00137                
  [2]  000000F [752588, 753724]      - |      EVM        mRNA      <NA>      <NA>             PCA_SD_00137-T1    PCA_SD_00137
  [3]  000000F [752588, 753724]      - |      EVM        exon      <NA>      <NA> evm.model.000000F.181.exon1 PCA_SD_00137-T1
  [4]  000000F [752588, 753724]      - |      EVM         CDS      <NA>         0   cds.evm.model.000000F.181 PCA_SD_00137-T1
  [5]  000000F [753722, 753724]      + |      EVM start_codon      <NA>      <NA>       PCA_SD_00137-T1:start PCA_SD_00137-T1
  [6]  000000F [752588, 752590]      + |      EVM  stop_codon      <NA>      <NA>        PCA_SD_00137-T1:stop PCA_SD_00137-T1
                    note         db_xref     go_function      go_process    go_component       prot_desc     product
         <CharacterList> <CharacterList> <CharacterList> <CharacterList> <CharacterList> <CharacterList> <character>
  [1]                                                                                                           <NA>
  [2] EggNog:ENOG410PTX5                                                                                        <NA>
  [3]                                                                                                           <NA>
  [4]                                                                                                           <NA>
  [5]                                                                                                           <NA>
  [6]                                                                                                           <NA>
  -------
  seqinfo: 1579 sequences from an unspecified genome; no seqlengths

Here's the code I've tried and the different error messages:

`sd80_gffgene <- getFeat2b(x=sd80_gff, format="GFF", group_col="gene_id", range_types=c("gene"))
Error in getFeat2b(x = sd80_gff, format = "GFF", group_col = "gene_id",  : 
  Specified group_col does not exist in granges object.`

`sd80_gffgene <- getFeat2b(x=sd80_gff, format="GFF", group_col="Parent", range_types=c("gene"))
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 2: negative widths are not allowed`

`sd80_gffgene <- getFeat2b(x=sd80_gff, format="GFF", group_col="ID", range_types=c("gene"))
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 2: negative widths are not allowed`

It seems like it might be some issue with my gff file but it's hard for me to say. Any ideas about this issue?

Thanks,
Marisa

**Comment by Adamtaranto** [comment] 2017-07-05 23:26
Have you edited that file in excel by any chance? Looks like the first record is on the same line as "##gff-version 3". 

Try cleaning up the line endings, like this if on mac:
```bash
dos2unix -c mac -o myfile.gff3
```

**Comment by Adamtaranto** [comment] 2017-07-05 23:44
The gff should also be tab delimited. Once fixed it will look like this:

>	##gff-version	3
>	000000F	EVM	gene	752588	753724	.	-	.	ID=PCA_SD_00137	
>	000000F	EVM	mRNA	752588	753724	.	-	.	ID=PCA_SD_00137-T1;Parent=PCA_SD_00137;note=EggNog:ENOG410PTX5
>	000000F	EVM	exon	752588	753724	.	-	.	ID=evm.model.000000F.181.exon1;Parent=PCA_SD_00137-T1
>	000000F	EVM	CDS	752588	753724	.	-	0	ID=cds.evm.model.000000F.181;Parent=PCA_SD_00137-T1
>	000000F	EVM	start_codon	753722	753724	.	+	.	ID=PCA_SD_00137-T1:start;Parent=PCA_SD_00137-T1
>	000000F	EVM	stop_codon	752588	752590	.	+	.	ID=PCA_SD_00137-T1:stop;Parent=PCA_SD_00137-T1
>	000000F	EVM	gene	748793	751796	.	+	.	ID=PCA_SD_00136
>	000000F	EVM	mRNA	748793	751796	.	+	.	ID=PCA_SD_00136-T1;Parent=PCA_SD_00136;note=EggNog:ENOG410PFEV,BUSCO:EOG09262A6N;db_xref=InterPro:IPR020472,InterPro:IPR001680,InterPro:IPR015943,InterPro:IPR032847,InterPro:IPR019775,InterPro:IPR017986;go_function=protein	binding|0005515||IEA;go_process=mRNA	splicing,	via	spliceosome|0000398||IEA;go_component=catalytic	step	2	spliceosome|0071013||IEA
>	000000F	EVM	exon	748793	749071	.	+	.	ID=evm.model.000000F.180.exon1;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	749168	749315	.	+	.	ID=evm.model.000000F.180.exon2;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	749458	750179	.	+	.	ID=evm.model.000000F.180.exon3;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	750261	750408	.	+	.	ID=evm.model.000000F.180.exon4;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	750520	750635	.	+	.	ID=evm.model.000000F.180.exon5;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	750736	750791	.	+	.	ID=evm.model.000000F.180.exon6;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	750896	751050	.	+	.	ID=evm.model.000000F.180.exon7;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	751151	751419	.	+	.	ID=evm.model.000000F.180.exon8;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	751517	751561	.	+	.	ID=evm.model.000000F.180.exon9;Parent=PCA_SD_00136-T1
>	000000F	EVM	exon	751791	751796	.	+	.	ID=evm.model.000000F.180.exon10;Parent=PCA_SD_00136-T1
>	

Then import and extract 'gene' records, labeled with 'ID' value.

```R
sd80_gff <- import.gff("myfile.gff3")
sd80_gffgene <- getFeat2b(x=sd80_gff, format="GFF", group_col="ID", range_types=c("gene")) 
```

**Comment by MarisaMiller** [comment] 2017-07-06 16:08
Hi Adam,

I didn't open this with excel, and I checked with cat -vet and it's definitely tab delimited. Also, the header is on a separate line.

I did some more digging about this error message:

` Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  solving row 2: negative widths are not allowed`

and it seems to be related to IRanges allowing negative widths. See [this](https://groups.google.com/forum/#!topic/davis-rug/NqJu8fZVnwU) post. I'm going to try to fix my gff file somehow!

Thanks,
Marisa

**Comment by MarisaMiller** [comment] 2017-07-06 16:15
By the way, here's the traceback:

```
Error in .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : solving row 2: negative widths are not allowed 

4. .Call2("solve_user_SEW0", start, end, width, PACKAGE = "IRanges") 

3. solveUserSEW0(start = start, end = end, width = width) 

2. IRanges(end(lastinter) + 1, chrend) at getFeat2b.R#84

1. getFeat2b(x = sd80_gff, format = "GFF", group_col = "ID", range_types = c("gene"))
```

And the section in getFeat2b that's unhappy:

`## Get range from chromosome end to last annotation feature                 
	chrend <-  seqlengths(x) 

	end <- tapply(end(gene), as.vector(seqnames(gene)), max)

	end <- paste(names(end), end, sep="_")

	all <- paste(as.vector(seqnames(gene)), end(gene), sep="_")

	lastinter <- gene[which(all %in% end),]

	lastinter <- unique(lastinter) 

	ranges(lastinter) <- IRanges(end(lastinter)+1, chrend) (****this is line 84)

	elementMetadata(lastinter)["group"] <- paste(as.character(as.data.frame(elementMetadata(lastinter)["group"])[,1]), "end", sep="_")`

**Comment by MarisaMiller** [comment] 2017-07-06 18:48
Ok I did some more digging (see [here](https://www.biostars.org/p/47095/)), and it seemed like the problem could be that the start positions were possibly not smaller than the end coordinates, hence a negative width. 

So I checked for that like so:

```
#Figure out what's going on with gff
sd80_test = read.csv("Puccinia_coronata_avenae_12SD80.nohead.gff3", sep="\t", header=FALSE)
sd80_test$width <- sd80_test$V5 - sd80_test$V4 
library(plyr)
test <- arrange(sd80_test,width)
```
But it looks like there are no negative widths and the smallest width is 2:

```
> head(test)
       V1  V2          V3     V4     V5 V6 V7 V8                                              V9 width
1 000000F EVM start_codon 753722 753724  .  +  . ID=PCA_SD_00137-T1:start;Parent=PCA_SD_00137-T1     2
2 000000F EVM  stop_codon 752588 752590  .  +  .  ID=PCA_SD_00137-T1:stop;Parent=PCA_SD_00137-T1     2
3 000000F EVM start_codon 748793 748795  .  +  . ID=PCA_SD_00136-T1:start;Parent=PCA_SD_00136-T1     2
4 000000F EVM  stop_codon 751794 751796  .  +  .  ID=PCA_SD_00136-T1:stop;Parent=PCA_SD_00136-T1     2
5 000000F EVM start_codon 746360 746362  .  +  . ID=PCA_SD_00135-T1:start;Parent=PCA_SD_00135-T1     2
6 000000F EVM  stop_codon 747897 747899  .  +  .  ID=PCA_SD_00135-T1:stop;Parent=PCA_SD_00135-T1     2
```

The only other thing I could think of is that genes on the - strand need to have the start and end coordinates reversed. However, I tested just a small portion of the gff file (only lines for contig 000000F without changing anything else about the file) and it worked without an error. So, this tells me there is something lurking in the file that is causing the error, but I'm not sure where. Is there anyway to have getFeat2b indicate the offending line number from the input gff? Then maybe I could figure out what's going on.

**Comment by Adamtaranto** [comment] 2017-07-07 04:18
Could you send me the full gff your are using? I'll try to recreate the issue. The subset you posted seems to run fine.

Also which version of IRanges do you have installed?

**Comment by MarisaMiller** [comment] 2017-07-07 18:14
Hi Adam,

Here are links for you to download the full gffs (I have two, but they both seem to have the same issue). https://s3.msi.umn.edu/nc29_Assembly/Puccinia_coronata_avenae_12NC29.gff3 and https://s3.msi.umn.edu/sd80_Assembly/Puccinia_coronata_avenae_12SD80.gff3

And below is my sessionInfo. It looks like I have IRanges v 2.10.2.

Thanks for the help!

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
 [1] grid      parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] fields_9.0           maps_3.2.0           spam_2.1-1           dotCall64_0.9-04     ggplot2_2.2.1        gridExtra_2.2.1     
 [7] png_0.1-7            Rsamtools_1.28.0     Biostrings_2.44.1    XVector_0.16.0       rtracklayer_1.36.3   GenomicRanges_1.28.3
[13] GenomeInfoDb_1.12.2  IRanges_2.10.2       S4Vectors_0.14.3     BiocGenerics_0.22.0 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11               zlibbioc_1.22.0            GenomicAlignments_1.12.1   munsell_0.4.3              BiocParallel_1.10.1       
 [6] colorspace_1.3-2           lattice_0.20-35            rlang_0.1.1                plyr_1.8.4                 tools_3.4.0               
[11] SummarizedExperiment_1.6.3 gtable_0.2.0               Biobase_2.36.2             matrixStats_0.52.2         lazyeval_0.2.0            
[16] tibble_1.3.3               Matrix_1.2-10              GenomeInfoDbData_0.99.0    bitops_1.0-6               RCurl_1.95-4.8            
[21] DelayedArray_0.2.7         compiler_3.4.0             scales_0.4.1               XML_3.98-1.9             
```

**Comment by Adamtaranto** [comment] 2017-07-08 01:12
Right, seems that the issue is resolved by removing the header row in the GFF, then sorting by Chromosome name, start, and end positions (each ascending) - "chrend" is then calculated correctly. This can be done with bash, else be sure to do the 'dos2unix' correction if you use excel.

I will add a fix for this later so that annotations do not need to be sorted.

**Closed as completed by Adamtaranto** 2017-07-08 01:12 UTC

**Comment by MarisaMiller** [comment] 2017-07-08 15:25
Hi Adam,

Thank you so much for the help! I sorted in the order you suggested (just using VIM) and it everything is working smoothly now. 

I do have a couple more questions for you, the first one related to bin selection. I did a comparison of TempBinLimits and BinLimits as suggested in the Saunders paper and am not sure how to interpret. In the paper, it says that the example plot with the P. infestans data has "significant reduction in the variance in bins with the proposed exponential regression." The trend I get with my data is a bit different but not sure if this in an issue or what I'm looking for.

Lastly, the paper also states that when comparisons of the architecture of several genomes is performed the same set of bin breaks might be required. I am comparing two isolates of the same species, and am wondering if I should export the bin breaks from one isolates (I guess it doesn't matter which, just pick one) and use those with the second isolate. Any suggestions here?

Thanks again for your help!
Marisa

![sd80_40_bins](https://user-images.githubusercontent.com/23660064/27986640-23c71690-63c7-11e7-9d7c-7ed32f628c1d.png)

**Comment by MarisaMiller** [comment] 2017-07-10 21:55
Hi Adam,

One other question as well. When I use 40 bins for the genome shown below I see lots of genes on the edges of contigs. Is this some kind of artifact with how the bins are created?

Thanks,
Marisa

![heat map_example](https://user-images.githubusercontent.com/23660064/28041858-895b1982-6590-11e7-9f2c-acf4c922d59d.png)

**Comment by Adamtaranto** [comment] 2017-08-07 01:43
Sorry for the slow reply, got lost in my inbox.

I don't think the diff trend-line should be an issue. You could try
extracting all records from the top and bottom 10-20% of bins from the
first round and use them as input to recall bin limits and make new
graphics - this ought to show you if the is any interesting structure in
the tails of your plot. If so you could include those as extra panels in
the final figure.

Yep, I would just pick one and export the breaks.

Adam

**Comment by Adamtaranto** [comment] 2017-08-07 01:49
I often see this as well. Do you mean ends of contigs or margins of the
plot?

If end of contig, 5' / 3' dist to the nearest gene will be something like
int / None and the record shouldn't get plotted.

If you mean the density spike along the margins in smallest bin and bottom
left corner, I suspect that this is the result of partially overlapping or
nested (isoforms?) gene records.

Adam
